PAISES_BANDERAS = {
    # Bilingual mapping (English left, Spanish right, or single entry)
    "Argentina": "ar",
    "Brazil": "br", "Brasil": "br",
    "Uruguay": "uy",
    "Colombia": "co",
    "France": "fr", "Francia": "fr",
    "Spain": "es", "España": "es",
    "England": "gb-eng", "Inglaterra": "gb-eng",
    "Germany": "de", "Alemania": "de",
    "Italy": "it", "Italia": "it",
    "Netherlands": "nl", "Países Bajos": "nl",
    "Portugal": "pt",
    "Belgium": "be", "Bélgica": "be",
    "Mexico": "mx", "México": "mx",
    "United States": "us", "USA": "us", "EE.UU.": "us", "EE. UU.": "us",
    "Canada": "ca", "Canadá": "ca",
    "Costa Rica": "cr",
    "Japan": "jp", "Japón": "jp",
    "South Korea": "kr", "Korea Republic": "kr", "Corea del Sur": "kr",
    "Saudi Arabia": "sa", "Arabia Saudita": "sa",
    "Australia": "au",
    "Morocco": "ma", "Marruecos": "ma",
    "Senegal": "sn",
    "Nigeria": "ng",
    "Cameroon": "cm", "Camerún": "cm",
    "South Africa": "za", "Sudáfrica": "za",
    "Chile": "cl",
    "Peru": "pe", "Perú": "pe",
    "Ecuador": "ec",
    "Paraguay": "py",
    "Bolivia": "bo",
    "Venezuela": "ve",
    "Panama": "pa", "Panamá": "pa",
    "Honduras": "hn",
    "Jamaica": "jm",
    "Haiti": "ht", "Haití": "ht",
    "Trinidad and Tobago": "tt", "Trinidad y Tobago": "tt",
    "Croatia": "hr", "Croacia": "hr",
    "Serbia": "rs",
    "Switzerland": "ch", "Suiza": "ch",
    "Denmark": "dk", "Dinamarca": "dk",
    "Sweden": "se", "Suecia": "se",
    "Norway": "no", "Noruega": "no",
    "Poland": "pl", "Polonia": "pl",
    "Ukraine": "ua", "Ucrania": "ua",
    "Czech Republic": "cz", "Czechia": "cz", "República Checa": "cz",
    "Austria": "at",
    "Hungary": "hu", "Hungría": "hu",
    "Romania": "ro", "Rumanía": "ro",
    "Scotland": "gb-sct", "Escocia": "gb-sct",
    "Wales": "gb-wls", "Gales": "gb-wls",
    "Ireland": "ie", "Irlanda": "ie", "Republic of Ireland": "ie",
    "Turkey": "tr", "Turquía": "tr",
    "Russia": "ru", "Rusia": "ru",
    "Greece": "gr", "Grecia": "gr",
    "Egypt": "eg", "Egipto": "eg",
    "Tunisia": "tn", "Túnez": "tn",
    "Algeria": "dz", "Argelia": "dz",
    "Ghana": "gh",
    "Ivory Coast": "ci", "Côte d'Ivoire": "ci", "Costa de Marfil": "ci",
    "DR Congo": "cd", "Congo": "cd",
    "Zambia": "zm",
    "Angola": "ao",
    "Iran": "ir", "Irán": "ir",
    "Iraq": "iq", "Irak": "iq",
    "Qatar": "qa", "Catar": "qa",
    "United Arab Emirates": "ae", "UAE": "ae", "Emiratos Árabes": "ae",
    "North Korea": "kp", "Korea DPR": "kp", "Corea del Norte": "kp",
    "China": "cn",
    "India": "in",
    "New Zealand": "nz", "Nueva Zelanda": "nz",
    "Fiji": "fj", "Fiyi": "fj",
    "Mali": "ml",
    "Burkina Faso": "bf",
    "Guinea": "gn",
    "Benin": "bj", "Benín": "bj",
    "Togo": "tg",
    "Sierra Leone": "sl", "Sierra Leona": "sl",
    "Sudan": "sd", "Sudán": "sd",
    "Guatemala": "gt",
    "El Salvador": "sv",
    "Nicaragua": "ni",
    "Cuba": "cu",
    "Dominican Republic": "do", "República Dominicana": "do",
    "Puerto Rico": "pr",
    "Bosnia and Herzegovina": "ba", "Bosnia": "ba",
    "Slovenia": "si", "Eslovenia": "si",
    "Slovakia": "sk", "Eslovaquia": "sk",
    "Albania": "al",
    "Iceland": "is", "Islandia": "is",
    "Finland": "fi", "Finlandia": "fi",
    "Montenegro": "me",
    "North Macedonia": "mk", "Macedonia": "mk",
    "Armenia": "am",
    "Georgia": "ge",
    "Azerbaijan": "az", "Azerbaiyán": "az",
    "Kazakhstan": "kz", "Kazajistán": "kz",
    "Israel": "il",
    "Jordan": "jo", "Jordania": "jo",
    "Lebanon": "lb", "Líbano": "lb",
    "Syria": "sy", "Siria": "sy",
    "Oman": "om", "Omán": "om",
    "Bahrain": "bh", "Baréin": "bh",
    "Kuwait": "kw",
    "Uzbekistan": "uz", "Uzbekistán": "uz",
    "Thailand": "th", "Tailandia": "th",
    "Vietnam": "vn",
    "Indonesia": "id",
    "Philippines": "ph", "Filipinas": "ph",
    "Malaysia": "my", "Malasia": "my",
    "Singapore": "sg", "Singapur": "sg",
    "Kenya": "ke",
    "Ethiopia": "et", "Etiopía": "et",
    "Tanzania": "tz",
    "Uganda": "ug",
    "Zimbabwe": "zw", "Zimbabue": "zw",
    "Mozambique": "mz",
    "Madagascar": "mg",
    "Mauritius": "mu", "Mauricio": "mu",
    "Cape Verde": "cv", "Cabo Verde": "cv",
    "Comoros": "km", "Comoras": "km",
    "Mauritania": "mr",
    "Niger": "ne", "Níger": "ne",
    "Chad": "td",
    "Central African Republic": "cf", "República Centroafricana": "cf",
    "Gabon": "ga", "Gabón": "ga",
    "Equatorial Guinea": "gq", "Guinea Ecuatorial": "gq",
    "Liberia": "lr",
    "Namibia": "na",
    "Botswana": "bw", "Botsuana": "bw",
    "Eswatini": "sz", "Swaziland": "sz", "Suazilandia": "sz",
    "Lesotho": "ls", "Lesoto": "ls",
    "Djibouti": "dj", "Yibuti": "dj",
    "Somalia": "so",
    "Rwanda": "rw", "Ruanda": "rw",
    "Burundi": "bi",
    "South Sudan": "ss", "Sudán del Sur": "ss",
    "Gambia": "gm",
    "Guinea-Bissau": "gw", "Guinea-Bisáu": "gw",
    "San Marino": "sm",
    "Andorra": "ad",
    "Luxembourg": "lu", "Luxemburgo": "lu",
    "Malta": "mt",
    "Cyprus": "cy", "Chipre": "cy",
    "Estonia": "ee",
    "Latvia": "lv", "Letonia": "lv",
    "Lithuania": "lt", "Lituania": "lt",
    "Bulgaria": "bg",
    "Moldova": "md",
    "Faroe Islands": "fo", "Islas Feroe": "fo",
    "Gibraltar": "gi",
    "Liechtenstein": "li",
    "Monaco": "mc", "Mónaco": "mc",
    "San Marino": "sm",
    "Vatican City": "va", "Vaticano": "va",
    "Kosovo": "xk",
    "Belarus": "by", "Bielorrusia": "by",
    "Brunei Darussalam": "bn", "Brunei": "bn",
    "Cambodia": "kh", "Camboya": "kh",
    "Laos": "la",
    "Myanmar": "mm",
    "Nepal": "np",
    "Pakistan": "pk", "Pakistán": "pk",
    "Sri Lanka": "lk",
    "Bangladesh": "bd",
    "Maldives": "mv", "Maldivas": "mv",
    "Mongolia": "mn",
    "Kyrgyzstan": "kg", "Kirguistán": "kg",
    "Tajikistan": "tj", "Tayikistán": "tj",
    "Turkmenistan": "tm",
    "Afghanistan": "af", "Afganistán": "af",
    "Bhutan": "bt", "Bután": "bt",
    "Timor-Leste": "tl", "East Timor": "tl",
    "Papua New Guinea": "pg", "Papúa Nueva Guinea": "pg",
    "New Caledonia": "nc", "Nueva Caledonia": "nc",
    "Tahiti": "pf", "French Polynesia": "pf",
    "Solomon Islands": "sb", "Islas Salomón": "sb",
    "Vanuatu": "vu",
    "Samoa": "ws",
    "Tonga": "to",
    "Cook Islands": "ck", "Islas Cook": "ck",
    "American Samoa": "as", "Samoa Americana": "as",
    "Guam": "gu",
    "Northern Ireland": "gb-nir", "Irlanda del Norte": "gb-nir",
    "Hong Kong": "hk",
    "Macau": "mo", "Macao": "mo",
    "Taiwan": "tw", "Chinese Taipei": "tw",
    "Palestine": "ps", "Palestina": "ps",
    "Yemen": "ye",
    "Libya": "ly", "Libia": "ly",
    "Seychelles": "sc",
    "São Tomé and Príncipe": "st", "Santo Tomé y Príncipe": "st",
    "Eritrea": "er",
    "Malawi": "mw",
    "Congo DR": "cd", "RD Congo": "cd",
    "Suriname": "sr", "Surinam": "sr",
    "Guyana": "gy",
    "Curaçao": "cw", "Curacao": "cw",
    "Aruba": "aw",
    "Bermuda": "bm", "Bermudas": "bm",
    "Barbados": "bb",
    "Grenada": "gd", "Granada": "gd",
    "Saint Kitts and Nevis": "kn", "San Cristóbal y Nieves": "kn",
    "Saint Lucia": "lc", "Santa Lucía": "lc",
    "Saint Vincent and the Grenadines": "vc", "San Vicente y las Granadinas": "vc",
    "Antigua and Barbuda": "ag", "Antigua y Barbuda": "ag",
    "Dominica": "dm",
    "Bahamas": "bs",
    "Belize": "bz", "Belice": "bz",
}
