PAISES_BANDERAS = {
    "Argentina": "ar", "Brasil": "br", "Uruguay": "uy", "Colombia": "co",
    "Francia": "fr", "España": "es", "Inglaterra": "gb-eng", "Alemania": "de",
    "Italia": "it", "Países Bajos": "nl", "Portugal": "pt", "Bélgica": "be",
    "México": "mx", "EE.UU.": "us", "Canadá": "ca", "Costa Rica": "cr",
    "Japón": "jp", "Corea del Sur": "kr", "Arabia Saudita": "sa", "Australia": "au",
    "Marruecos": "ma", "Senegal": "sn", "Nigeria": "ng", "Camerún": "cm",
    "South Africa": "za", "Chile": "cl", "Perú": "pe", "Ecuador": "ec",
    "Paraguay": "py", "Bolivia": "bo", "Venezuela": "ve", "Panamá": "pa",
    "Honduras": "hn", "Jamaica": "jm", "Haití": "ht", "Trinidad y Tobago": "tt",
    "Croacia": "hr", "Serbia": "rs", "Suiza": "ch", "Dinamarca": "dk",
    "Suecia": "se", "Noruega": "no", "Polonia": "pl", "Ucrania": "ua",
    "República Checa": "cz", "Austria": "at", "Hungría": "hu", "Rumanía": "ro",
    "Escocia": "gb-sct", "Gales": "gb-wls", "Irlanda": "ie",
    "Turquía": "tr", "Rusia": "ru", "Grecia": "gr",
    "Egipto": "eg", "Túnez": "tn", "Argelia": "dz", "Ghana": "gh",
    "Costa de Marfil": "ci", "Congo": "cd", "Zambia": "zm", "Angola": "ao",
    "Irán": "ir", "Irak": "iq", "Catar": "qa", "Emiratos Árabes": "ae",
    "Corea del Norte": "kp", "China": "cn", "India": "in",
    "Nueva Zelanda": "nz", "Fiyi": "fj",
    "Mali": "ml", "Burkina Faso": "bf", "Guinea": "gn", "Benín": "bj",
    "Togo": "tg", "Sierra Leona": "sl", "Sudán": "sd",
    "Guatemala": "gt", "El Salvador": "sv", "Nicaragua": "ni", "Cuba": "cu",
    "República Dominicana": "do", "Puerto Rico": "pr",
    "Bosnia": "ba", "Eslovenia": "si", "Eslovaquia": "sk", "Albania": "al",
    "Islandia": "is", "Finlandia": "fi", "Montenegro": "me", "Macedonia": "mk",
    "Armenia": "am", "Georgia": "ge", "Azerbaiyán": "az", "Kazajistán": "kz",
    "Israel": "il", "Jordania": "jo", "Líbano": "lb", "Siria": "sy",
    "Omán": "om", "Baréin": "bh", "Kuwait": "kw", "Uzbekistán": "uz",
    "Tailandia": "th", "Vietnam": "vn", "Indonesia": "id", "Filipinas": "ph",
    "Malasia": "my", "Singapur": "sg",
    "Kenya": "ke", "Etiopía": "et", "Tanzania": "tz", "Uganda": "ug",
    "Zimbabue": "zw", "Mozambique": "mz", "Madagascar": "mg", "Mauricio": "mu",
    "Cabo Verde": "cv", "Comoras": "km", "Mauritania": "mr", "Níger": "ne",
    "Chad": "td", "República Centroafricana": "cf", "Gabón": "ga", "Guinea Ecuatorial": "gq",
    "Liberia": "lr", "Namibia": "na", "Botsuana": "bw", "Suazilandia": "sz",
    "Lesoto": "ls", "Yibuti": "dj", "Somalia": "so", "Ruanda": "rw",
    "Burundi": "bi", "Sudán del Sur": "ss", "Gambia": "gm", "Guinea-Bisáu": "gw",
}
